[env]
term = "xterm-256color"

[general]
import = [
    "~/.config/alacritty/themes/themes/everforest_dark.toml"
]

[font]
normal.family = "JetBrainsMono Nerd Font"
normal.style = "Regular"
size = 12.0

[window]
padding.x = 10
padding.y = 10
decorations = "buttonless"
opacity = 0.8
blur = true
option_as_alt = "Both"
